using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Newtonsoft.Json;
using UnityEditor;
using UnityEngine;
using WS_Modules.LogModule;

namespace WS_Modules.UIModule
{
    public static class WindowBindDataCompGeneratorTool
    {
        public static List<EditorObjectData> objDataList; //查找对象的数据
        private static WSFrameSetting setting;
        private static string nameSpaceName = "WS_Modules.UIModule";
        private const string BindDataGeneratorTargetIdKey = "BindDataGeneratorTargetInstanceId";

        private static WSFrameSetting GetSetting()
        {
            var settings = AssetDatabase.FindAssets("t:WSFrameSetting");
            if (settings.Length == 0)
            {
                Debug.LogError("Can not find WSFrameSetting asset.");
                return null;
            }
            var path = AssetDatabase.GUIDToAssetPath(settings[0]);
            return AssetDatabase.LoadAssetAtPath<WSFrameSetting>(path);
        }
        
        [MenuItem("GameObject/UI自动绑定工具/生成组件数据脚本(Shift+B) #B", false, 0)]
        internal static void CreateFindComponentScripts()
        {
            GameObject obj = Selection.objects.First() as GameObject; //获取到当前选择的物体
            if (obj == null)
            {
                Debug.LogError("需要选择 GameObject");
                return;
            }

            int targetInstanceId = obj.GetInstanceID();

            objDataList = new List<EditorObjectData>();
            setting = WSFrameRoot.Instance?.FrameSetting ?? GetSetting(); 
            nameSpaceName = setting.uiManagerSetting.BindComponentNameSpace;

            //设置脚本生成路径
            if (!Directory.Exists(setting.uiManagerSetting.BindComponentGeneratorPath))
            {
                Directory.CreateDirectory(setting.uiManagerSetting.BindComponentGeneratorPath);
            }

            //解析窗口组件数据
            AnalysisComponentDataTool.AnalysisWindowNodeData(ref objDataList, obj.transform, obj.name);

            if (!ValidateObjectDataTypes(objDataList))
            {
                return;
            }

            //储存字段名称
            string datalistJson = JsonConvert.SerializeObject(objDataList);
            PlayerPrefs.SetString(GeneratorConfig.OBJDATALIST_KEY, datalistJson);
            //生成CS脚本
            string csContnet = GenerateScript(obj.name);
            
            string scriptPath = setting.uiManagerSetting.BindComponentGeneratorPath + "/" + obj.name + "DataComponent.cs";
            ScriptDisplayWindow.ShowWindow(
                csContnet,
                scriptPath,
                fieldList: objDataList,
                isBindData: true,
                onBeforeGenerate: () =>
                {
                    // 仅在用户点击生成脚本后写入回调状态，避免取消生成后残留状态误绑定层级对象。
                    EditorPrefs.SetInt(BindDataGeneratorTargetIdKey, targetInstanceId);
                    EditorPrefs.SetString("BindDataGeneratorClassPath", scriptPath);
                });
        }

        public static string GenerateScript(string name)
        {
            StringBuilder sb = new StringBuilder();
            
            //添加引用
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// 此文件由 WSFrame 自动生成。");
            sb.AppendLine("// 该文件用于维护 UI 组件字段、组件引用和 InitComponent 事件绑定。");
            sb.AppendLine("// 该文件可能会在下次生成时被整体覆盖，请不要在此文件中手写业务逻辑。");
            sb.AppendLine("// 如需扩展功能，请在对应 WindowCode 或同名 partial 类的非生成文件中编写。");
            sb.AppendLine("// </auto-generated>");
            foreach (string nameSpace in setting.uiManagerSetting.UsingNameSpaceArr)
            {
                sb.AppendLine($"using {nameSpace};");
            }

            sb.AppendLine();

            //生成命名空间
            if (!string.IsNullOrEmpty(nameSpaceName))
            {
                sb.AppendLine($"namespace {nameSpaceName}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"\tpublic class {name + "Data" + "Component : MonoBehaviour"}");
            sb.AppendLine("\t{");
            sb.AppendLine("\t\t//窗口配置");
            sb.AppendLine("\t\tpublic bool IsFullWindow;");
            sb.AppendLine("\t\tpublic bool DoAnimation = true;\n");
            sb.AppendLine("\t\t//自定义字段");

            //根据字段数据列表 声明字段
            foreach (var item in objDataList)
            {
                if (item.dataList != null)
                {
                    sb.AppendLine($"\t\tpublic {item.fieldType}[] {item.fieldName}{item.fieldType}Array;\n");
                }
                else
                {
                    sb.AppendLine("\t\tpublic " + item.fieldType + " " + item.fieldName + item.fieldType + ";\n");
                }
            }

            //声明初始化组件接口
            sb.AppendLine("\t\tpublic void InitComponent(WindowBase target)");
            sb.AppendLine("\t\t{");

            sb.AppendLine("\t\t     //组件事件绑定");
            //得到逻辑类 WindowBase => LoginWindow
            sb.AppendLine($"\t\t     {name} mWindow=({name})target;");

            //生成UI事件绑定代码
            foreach (var item in objDataList)
            {
                string type = item.fieldType;
                string methodName = item.fieldName;
                string suffix;
                if (type.Contains("Button"))
                {
                    suffix = "Click";
                    sb.AppendLine(
                        $"\t\t     target.AddButtonClickListener({methodName}{type},mWindow.On{methodName}Button{suffix});");
                }

                if (type.Contains("InputField"))
                {
                    sb.AppendLine(
                        $"\t\t     target.AddInputFieldListener({methodName}{type},mWindow.On{methodName}InputChange,mWindow.On{methodName}InputEnd);");
                }

                if (type.Contains("Toggle"))
                {
                    suffix = "Change";
                    sb.AppendLine(
                        $"\t\t     target.AddToggleClickListener({methodName}{type},mWindow.On{methodName}Toggle{suffix});");
                }
            }

            sb.AppendLine("\t\t}");
            sb.AppendLine("\t}");
            if (!string.IsNullOrEmpty(nameSpaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }


        [MenuItem("GameObject/UI自动绑定工具/手动绑定组件", false, 0)]
        internal static void ManualBindComponents()
        {
            GameObject obj = Selection.objects.First() as GameObject; //获取到当前选择的物体
            if (obj == null)
            {
                Debug.LogError("需要选择 GameObject");
                return;
            }

            string className = $"{nameSpaceName}." + obj.name + "DataComponent";
            var targetScript = GetType(className);

            if (targetScript == null)
            {
                Debug.LogError($"找不到对应的组件脚本: {className}");
                return;
            }
            
            //获取要挂载的那个物体
            GameObject selectedObject = Selection.activeGameObject;
            if (selectedObject == null)
                return;

            //先获取现窗口上有没有挂载该数据组件，如果没挂载在进行挂载
            Component compt = selectedObject.GetComponent(targetScript);
            if (compt == null)
            {
                compt = selectedObject.AddComponent(targetScript);
            }
            
            objDataList = new List<EditorObjectData>();
            //解析窗口组件数据
            AnalysisComponentDataTool.AnalysisWindowNodeData(ref objDataList, obj.transform, obj.name);

            if (!ValidateObjectDataTypes(objDataList))
            {
                return;
            }
            
            //获取脚本所有字段
            FieldInfo[] fieldInfoList = targetScript.GetFields();

            foreach (var item in fieldInfoList)
            {
                foreach (var objData in objDataList)
                {
                    if (item.Name == $"{objData.fieldName}{objData.fieldType}" ||
                        item.Name == $"{objData.fieldName}{objData.fieldType}Array")
                    {
                        // 已有引用则不覆盖（避免清空手动绑定）
                        object currentValue = item.GetValue(compt);
                        if (currentValue != null)
                        {
                            // 数组为空时才允许补值
                            if (currentValue is Array existingArray && existingArray.Length == 0)
                            {
                                // 继续执行补齐逻辑
                            }
                            else
                            {
                                break;
                            }
                        }

                        // 根据 InstanceID 或名称回退查找对象，避免重载后丢失引用
                        GameObject uiObject = ResolveUiObject(selectedObject.transform, objData);
                        if (uiObject == null)
                        {
                            // 找不到对象时不覆盖已有字段
                            break;
                        }
                        if (objData.dataList == null)
                        {
                            //设置该字段所对应的对象
                            if (string.Equals(objData.fieldType, "GameObject"))
                            {
                                item.SetValue(compt, uiObject);
                            }
                            else
                            {
                                object component = uiObject?.GetComponent(objData.fieldType);
                                if (component == null)
                                {
                                    var componentType = GetType($"TMPro.{objData.fieldType}");
                                    if (componentType != null)
                                    {
                                        component = uiObject?.GetComponent(componentType);
                                    }
                                }
                                if (component == null)
                                {
                                    WSLog.LogError($"Component of type {objData.fieldType} not found on GameObject {uiObject?.name}!");
                                    break;
                                }
                                item.SetValue(compt, component);
                            }
                        }
                        else
                        {
                            if (objData.fieldType.Contains("GameObject"))
                            {
                                GameObject[] newArray = new GameObject[objData.dataList.Count];
                                for (int i = 0; i < objData.dataList.Count; i++)
                                {
                                    newArray[i] =
                                        EditorUtility.InstanceIDToObject(objData.dataList[i].insID) as GameObject;
                                    if (newArray[i] == null)
                                    {
                                        // 回退：从父节点子物体中按名称查找
                                        newArray[i] = FindChildByName(uiObject?.transform, objData.dataList[i].fieldName);
                                    }
                                }

                                // 过滤空引用，避免覆盖为全空数组
                                if (newArray.All(x => x == null))
                                {
                                    break;
                                }
                                item.SetValue(compt, newArray);
                            }
                            else
                            {
                                // 获取数组类型
                                Type arrayType = item.FieldType;
                                // 获取数组元素类型
                                Type elementType = arrayType.GetElementType();
                                //获取该节点下的所有的物体
                                Component[] components = uiObject?.GetComponentsInChildren(elementType);
                                if (elementType is null || components == null || components.Length == 0)
                                {
                                    WSLog.LogError($"Failed to get components of type {objData.fieldType} from GameObject {uiObject?.name}!");
                                    break;
                                }
                                // 创建目标数组
                                Array targetArray = Array.CreateInstance(elementType, components.Length);

                                // 将组件赋值给目标数组
                                for (int i = 0; i < components.Length; i++)
                                {
                                    if (components[i] != null && elementType.IsAssignableFrom(components[i].GetType()))
                                    {
                                        targetArray.SetValue(components[i], i);
                                    }
                                    else
                                    {
                                        Debug.LogError($"Element at index {i} is not of type {elementType.Name}!");
                                    }
                                }

                                // 设置字段的值
                                item.SetValue(compt, targetArray);
                            }
                        }

                        break;
                    }
                }
            }

            //自动保存预制体
            if (AnalysisComponentDataTool.IsPrefabInstance(selectedObject))
            {
                PrefabUtility.ApplyPrefabInstance(selectedObject, InteractionMode.AutomatedAction);
            }
            Debug.Log("手动绑定组件成功!");
        }

        private static bool ValidateObjectDataTypes(List<EditorObjectData> dataList)
        {
            if (dataList == null || dataList.Count == 0)
            {
                return true;
            }

            List<string> invalidFields = new List<string>();
            foreach (EditorObjectData data in dataList)
            {
                Type type = ResolveComponentType(data.fieldType);
                if (type == null)
                {
                    invalidFields.Add($"[{data.fieldType}]{data.fieldName}");
                }
            }

            if (invalidFields.Count == 0)
            {
                return true;
            }

            Debug.LogError("UI 自动绑定生成失败，以下节点的组件类型无法识别：\n" +
                           string.Join("\n", invalidFields) +
                           "\n请检查节点命名，或在 WSFrameSetting.UIManagerSetting.UsingNameSpaceArr 中加入对应命名空间。");
            return false;
        }

        private static Type ResolveComponentType(string typeName)
        {
            if (string.IsNullOrEmpty(typeName))
            {
                return null;
            }

            if (string.Equals(typeName, nameof(GameObject), StringComparison.Ordinal))
            {
                return typeof(GameObject);
            }

            Type type = GetType(typeName);
            if (type != null)
            {
                return type;
            }

            List<string> commonNamespaces = new List<string>
            {
                "UnityEngine",
                "UnityEngine.UI",
                "TMPro",
                nameSpaceName
            };

            if (setting?.uiManagerSetting?.UsingNameSpaceArr != null)
            {
                commonNamespaces.AddRange(setting.uiManagerSetting.UsingNameSpaceArr);
            }

            foreach (string namespaceName in commonNamespaces)
            {
                if (string.IsNullOrEmpty(namespaceName))
                {
                    continue;
                }

                type = GetType($"{namespaceName}.{typeName}");
                if (type != null)
                {
                    return type;
                }
            }

            return null;
        }

        private static Type GetType(string typeName)
        {
            var type = Type.GetType(typeName);
            if (type != null) return type;
            foreach (var a in AppDomain.CurrentDomain.GetAssemblies())
            {
                type = a.GetType(typeName);
                if (type != null)
                    return type;
            }
            return null;
        }

        private static GameObject ResolveUiObject(Transform root, EditorObjectData data)
        {
            GameObject uiObject = EditorUtility.InstanceIDToObject(data.insID) as GameObject;
            if (uiObject != null || root == null)
            {
                return uiObject;
            }

            // 回退：按字段名从层级查找（适配实例 ID 失效或对象重建）
            return FindNodeByFieldName(root, data.fieldName);
        }

        private static GameObject FindNodeByFieldName(Transform root, string fieldName)
        {
            if (root == null || string.IsNullOrEmpty(fieldName))
            {
                return null;
            }

            Stack<Transform> stack = new Stack<Transform>();
            stack.Push(root);
            while (stack.Count > 0)
            {
                Transform current = stack.Pop();
                string currentFieldName = ExtractFieldName(current.name);
                if (!string.IsNullOrEmpty(currentFieldName) && currentFieldName == fieldName)
                {
                    return current.gameObject;
                }

                for (int i = 0; i < current.childCount; i++)
                {
                    stack.Push(current.GetChild(i));
                }
            }

            return null;
        }

        private static GameObject FindChildByName(Transform parent, string childName)
        {
            if (parent == null || string.IsNullOrEmpty(childName))
            {
                return null;
            }

            for (int i = 0; i < parent.childCount; i++)
            {
                Transform child = parent.GetChild(i);
                if (string.Equals(child.name, childName, StringComparison.Ordinal))
                {
                    return child.gameObject;
                }
            }

            return null;
        }

        private static string ExtractFieldName(string nodeName)
        {
            if (string.IsNullOrEmpty(nodeName) || !nodeName.Contains("[") || !nodeName.Contains("]"))
            {
                return null;
            }

            int index = nodeName.IndexOf("]", StringComparison.Ordinal) + 1;
            if (index <= 0 || index >= nodeName.Length)
            {
                return null;
            }

            string fieldName = nodeName.Substring(index, nodeName.Length - index);
            return System.Text.RegularExpressions.Regex.Replace(fieldName.Trim(), @"\p{C}", "");
        }

        /// <summary>
        /// 编译完成系统自动调用
        /// </summary>
        [UnityEditor.Callbacks.DidReloadScripts]
        public static void AddComponent2Window()
        {
            //如果当前不是生成数据脚本的回调，就不处理
            string scriptPath = EditorPrefs.GetString("BindDataGeneratorClassPath");
            if (string.IsNullOrEmpty(scriptPath))
            {
                return;
            }

            // 读取生成时记录的目标对象
            int targetId = EditorPrefs.GetInt(BindDataGeneratorTargetIdKey, 0);
            GameObject selectedObject = targetId != 0
                ? EditorUtility.InstanceIDToObject(targetId) as GameObject
                : null;
            if (selectedObject == null)
            {
                Debug.LogWarning("生成回调未找到目标对象，已跳过自动挂载。");
                EditorPrefs.DeleteKey("BindDataGeneratorClassPath");
                EditorPrefs.DeleteKey(BindDataGeneratorTargetIdKey);
                return;
            }

            //1.通过反射的方式，从程序集中找到这个脚本，把它挂在到当前的物体上
            //获取所有的程序集
            var targetScript = AssetDatabase.LoadAssetAtPath<MonoScript>(scriptPath)?.GetClass();
            if (targetScript == null)
            {
                Debug.Log("Failed to load script!");
                EditorPrefs.DeleteKey("BindDataGeneratorClassPath");
                EditorPrefs.DeleteKey(BindDataGeneratorTargetIdKey);
                return;
            }

            //先获取现窗口上有没有挂载该数据组件，如果没挂载在进行挂载
            Component compt = selectedObject.GetComponent(targetScript);
            if (compt == null)
            {
                compt = selectedObject.AddComponent(targetScript);
            }

            //2.通过反射的方式，遍历数据列表 找到对应的字段，赋值
            //获取对象数据列表
            string datalistJson = PlayerPrefs.GetString(GeneratorConfig.OBJDATALIST_KEY);
            List<EditorObjectData> objDataList = JsonConvert.DeserializeObject<List<EditorObjectData>>(datalistJson);
            //获取脚本所有字段
            FieldInfo[] fieldInfoList = targetScript.GetFields();

            foreach (var item in fieldInfoList)
            {
                foreach (var objData in objDataList)
                {
                    if (item.Name == $"{objData.fieldName}{objData.fieldType}" ||
                        item.Name == $"{objData.fieldName}{objData.fieldType}Array")
                    {
                        // 已有引用则不覆盖（避免清空手动绑定）
                        object currentValue = item.GetValue(compt);
                        if (currentValue != null)
                        {
                            // 数组为空时才允许补值
                            if (currentValue is Array existingArray && existingArray.Length == 0)
                            {
                                // 继续执行补齐逻辑
                            }
                            else
                            {
                                break;
                            }
                        }

                        // 根据 InstanceID 或名称回退查找对象，避免重载后丢失引用
                        GameObject uiObject = ResolveUiObject(selectedObject.transform, objData);
                        if (uiObject == null)
                        {
                            // 找不到对象时不覆盖已有字段
                            break;
                        }
                        if (objData.dataList == null)
                        {
                            //设置该字段所对应的对象
                            if (string.Equals(objData.fieldType, "GameObject"))
                            {
                                item.SetValue(compt, uiObject);
                            }
                            else
                            {
                                object component = uiObject?.GetComponent(objData.fieldType);
                                if (component == null)
                                {
                                    var componentType = GetType($"TMPro.{objData.fieldType}");
                                    if (componentType != null)
                                    {
                                        component = uiObject?.GetComponent(componentType);
                                    }
                                }
                                if (component == null)
                                {
                                    WSLog.LogError($"Component of type {objData.fieldType} not found on GameObject {uiObject?.name}!");
                                    break;
                                }
                                item.SetValue(compt, component);
                            }
                        }
                        else
                        {
                            if (objData.fieldType.Contains("GameObject"))
                            {
                                GameObject[] newArray = new GameObject[objData.dataList.Count];
                                for (int i = 0; i < objData.dataList.Count; i++)
                                {
                                    newArray[i] =
                                        EditorUtility.InstanceIDToObject(objData.dataList[i].insID) as GameObject;
                                    if (newArray[i] == null)
                                    {
                                        // 回退：从父节点子物体中按名称查找
                                        newArray[i] = FindChildByName(uiObject?.transform, objData.dataList[i].fieldName);
                                    }
                                }

                                // 过滤空引用，避免覆盖为全空数组
                                if (newArray.All(x => x == null))
                                {
                                    break;
                                }
                                item.SetValue(compt, newArray);
                            }
                            else
                            {
                                // 获取数组类型
                                Type arrayType = item.FieldType;
                                // 获取数组元素类型
                                Type elementType = arrayType.GetElementType();
                                //获取该节点下的所有的物体
                                Component[] components = uiObject?.GetComponentsInChildren(elementType);
                                if (elementType is null || components == null || components.Length == 0)
                                {
                                    WSLog.LogError($"Failed to get components of type {objData.fieldType} from GameObject {uiObject?.name}!");
                                    break;
                                }
                                // 创建目标数组
                                Array targetArray = Array.CreateInstance(elementType, components.Length);

                                // 将组件赋值给目标数组
                                for (int i = 0; i < components.Length; i++)
                                {
                                    if (components[i] != null && elementType.IsAssignableFrom(components[i].GetType()))
                                    {
                                        targetArray.SetValue(components[i], i);
                                    }
                                    else
                                    {
                                        Debug.LogError($"Element at index {i} is not of type {elementType.Name}!");
                                    }
                                }

                                // 设置字段的值
                                item.SetValue(compt, targetArray);
                            }
                        }

                        break;
                    }
                }
            }

            EditorPrefs.DeleteKey("BindDataGeneratorClassPath");
            EditorPrefs.DeleteKey(BindDataGeneratorTargetIdKey);
            //自动保存预制体
            if (AnalysisComponentDataTool.IsPrefabInstance(selectedObject))
            {
                PrefabUtility.ApplyPrefabInstance(selectedObject, InteractionMode.AutomatedAction);
            }
        }


        public static Array ConvertArray(object[] sourceArray, Type targetElementType)
        {
            // 创建目标数组
            Array targetArray = Array.CreateInstance(targetElementType, sourceArray.Length);

            // 将元素赋值给目标数组
            for (int i = 0; i < sourceArray.Length; i++)
            {
                if (sourceArray[i] != null && targetElementType.IsAssignableFrom(sourceArray[i].GetType()))
                {
                    targetArray.SetValue(sourceArray[i], i);
                }
                else
                {
                    throw new InvalidCastException($"Element at index {i} cannot be cast to {targetElementType.Name}!");
                }
            }

            return targetArray;
        }
    }
}

