// <auto-generated>
// This file is generated by WSFrame.
// It stores UI component references and InitComponent event bindings.
// Business logic should live in the matching WindowCode partial class.
// </auto-generated>
using UnityEngine;
using UnityEngine.UI;

namespace WS_Modules.UIModule
{
    public class GlobalUIWindowDataComponent : MonoBehaviour
    {
        public bool IsFullWindow;
        public bool DoAnimation = true;

        public InventoryBarView BarFrameInventoryBarView;
        public ToolCursorView ToolCursorView;
        public TimeUIView TimeUIView;
        public Button BagButton;

        public void InitComponent(WindowBase target)
        {
            GlobalUIWindow window = (GlobalUIWindow)target;
            target.AddButtonClickListener(BagButton, window.OnBagButtonClick);
        }
    }
}
