// <auto-generated>
// 此文件由 WSFrame 自动生成。
// 该文件用于维护 UI 组件字段、组件引用和 InitComponent 事件绑定。
// 该文件可能会在下次生成时被整体覆盖，请不要在此文件中手写业务逻辑。
// 如需扩展功能，请在对应 WindowCode 或同名 partial 类的非生成文件中编写。
// </auto-generated>
using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace WS_Modules.UIModule
{
	public class TestWindow2DataComponent : MonoBehaviour
	{
		//窗口配置
		public bool IsFullWindow;
		public bool DoAnimation = true;

		//自定义字段
		public Image ImageImage;

		public void InitComponent(WindowBase target)
		{
		     //组件事件绑定
		     TestWindow2 mWindow=(TestWindow2)target;
		}
	}
}
