// <auto-generated>
// 此文件由 WSFrame 自动生成。
// 该文件用于维护 WindowCode 的自动绑定字段和绑定入口。
// 该文件可能会在下次生成时被整体覆盖，请不要在此文件中手写业务逻辑。
// UI 事件方法和窗口业务逻辑请写在同名 WindowCode 主文件中。
// </auto-generated>
namespace WS_Modules.UIModule
{
    public partial class TestWindow
    {
        public TestWindowDataComponent dataCompt;

        private void BindGeneratedComponents()
        {
            dataCompt = GameObject.GetComponent<TestWindowDataComponent>();
            FullScreenWindow = dataCompt.IsFullWindow;
            SetDoAnimation(dataCompt.DoAnimation);
            dataCompt.InitComponent(this);
        }
    }
}
