using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace WS_Modules.Pooling.Editor
{
    public static class ClassPoolPrewarmRegistryGenerator
    {
        private const string GeneratedFilePath =
            "Assets/Scripts/WSFrame/Pooling/Generated/ClassPoolPrewarmRegistry.generated.cs";

        [MenuItem("Tools/WSFrame/Pooling/Generate Class Pool Prewarm Registry", priority = 2000)]
        public static void Generate()
        {
            var candidates = TypeCache.GetTypesDerivedFrom<IPoolable>()
                .Where(IsSelectableType)
                .OrderBy(type => type.FullName, StringComparer.Ordinal)
                .Select(CreateCandidate)
                .ToList();

            // 检查 hash 冲突
            EnsureNoIdConflicts(candidates);
            WriteRegistry(candidates);
            AssetDatabase.Refresh();
            Debug.Log($"Generated class pool prewarm registry. Count: {candidates.Count}");
        }

        [MenuItem("Assets/WSFrame/Pooling/Refresh Class Pool Prewarm Registry", false, 2000)]
        private static void GenerateFromSelectedPoolPrewarmConfig()
        {
            Generate();
        }

        [MenuItem("Assets/WSFrame/Pooling/Refresh Class Pool Prewarm Registry", true)]
        private static bool CanGenerateFromSelectedPoolPrewarmConfig()
        {
            return Selection.activeObject is PoolPrewarmConfig;
        }

        [MenuItem("CONTEXT/PoolPrewarmConfig/Refresh Class Pool Prewarm Registry")]
        private static void GenerateFromPoolPrewarmConfigContext(MenuCommand command)
        {
            Generate();
        }

        private static bool IsSelectableType(Type type)
        {
            return type != null
                   && type.Assembly.GetName().Name == "Assembly-CSharp"
                   && typeof(IPoolable).IsAssignableFrom(type)
                   && !typeof(MonoBehaviour).IsAssignableFrom(type)
                   && type is { IsClass: true, IsAbstract: false, IsGenericTypeDefinition: false, IsGenericType: false }
                   && (type.IsPublic || type.IsNestedPublic)
                   && type.GetConstructor(Type.EmptyTypes) != null;
        }

        private static Candidate CreateCandidate(Type type)
        {
            var fullName = type.FullName ?? type.Name;
            return new Candidate
            {
                Type = type,
                Id = GetStableId(fullName),
                EnumName = $"{SanitizeIdentifier(fullName)}_{GetStableId(fullName):X}",
                TypeReference = $"global::{fullName.Replace("+", ".")}",
                DisplayName = $"{fullName} ({type.Assembly.GetName().Name})",
            };
        }

        private static void EnsureNoIdConflicts(List<Candidate> candidates)
        {
            var usedIds = new Dictionary<int, Candidate>();
            foreach (var candidate in candidates)
            {
                if (!usedIds.TryGetValue(candidate.Id, out var existing))
                {
                    usedIds[candidate.Id] = candidate;
                    continue;
                }

                throw new InvalidOperationException(
                    $"Class pool prewarm id conflict: {existing.Type.FullName} and {candidate.Type.FullName} both use {candidate.Id}.");
            }
        }

        private static void WriteRegistry(List<Candidate> candidates)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// Generated by ClassPoolPrewarmRegistryGenerator.");
            builder.AppendLine("// Do not edit this file manually.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine();
            builder.AppendLine("namespace WS_Modules.Pooling");
            builder.AppendLine("{");
            builder.AppendLine("    public enum ClassPoolPrewarmId");
            builder.AppendLine("    {");
            builder.AppendLine("        None = 0,");
            foreach (var candidate in candidates)
            {
                builder.AppendLine($"        {candidate.EnumName} = {candidate.Id},");
            }

            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public readonly struct ClassPoolPrewarmRegistryEntry");
            builder.AppendLine("    {");
            builder.AppendLine("        public readonly ClassPoolPrewarmId Id;");
            builder.AppendLine("        public readonly Type Type;");
            builder.AppendLine("        public readonly string DisplayName;");
            builder.AppendLine("        public readonly Action<ClassPoolModule, int, int> Apply;");
            builder.AppendLine();
            builder.AppendLine("        public ClassPoolPrewarmRegistryEntry(ClassPoolPrewarmId id, Type type, string displayName,");
            builder.AppendLine("            Action<ClassPoolModule, int, int> apply)");
            builder.AppendLine("        {");
            builder.AppendLine("            Id = id;");
            builder.AppendLine("            Type = type;");
            builder.AppendLine("            DisplayName = displayName;");
            builder.AppendLine("            Apply = apply;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public static class ClassPoolPrewarmRegistry");
            builder.AppendLine("    {");
            builder.AppendLine("        private static readonly ClassPoolPrewarmRegistryEntry[] EntriesValue =");
            builder.AppendLine("        {");
            foreach (var candidate in candidates)
            {
                builder.AppendLine("            new(");
                builder.AppendLine($"                ClassPoolPrewarmId.{candidate.EnumName},");
                builder.AppendLine($"                typeof({candidate.TypeReference}),");
                builder.AppendLine($"                \"{EscapeString(candidate.DisplayName)}\",");
                builder.AppendLine($"                (module, count, capacity) => module.Prewarm<{candidate.TypeReference}>(count, capacity)),");
            }

            builder.AppendLine("        };");
            builder.AppendLine();
            builder.AppendLine("        private static readonly Dictionary<ClassPoolPrewarmId, ClassPoolPrewarmRegistryEntry> EntryMap = new();");
            builder.AppendLine();
            builder.AppendLine("        static ClassPoolPrewarmRegistry()");
            builder.AppendLine("        {");
            builder.AppendLine("            foreach (var entry in EntriesValue)");
            builder.AppendLine("            {");
            builder.AppendLine("                EntryMap[entry.Id] = entry;");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        public static IReadOnlyList<ClassPoolPrewarmRegistryEntry> Entries => EntriesValue;");
            builder.AppendLine();
            builder.AppendLine("        public static bool TryGetEntry(ClassPoolPrewarmId id, out ClassPoolPrewarmRegistryEntry entry)");
            builder.AppendLine("        {");
            builder.AppendLine("            return EntryMap.TryGetValue(id, out entry);");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        public static string GetDisplayName(ClassPoolPrewarmId id)");
            builder.AppendLine("        {");
            builder.AppendLine("            return TryGetEntry(id, out var entry) ? entry.DisplayName : string.Empty;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            File.WriteAllText(GeneratedFilePath, builder.ToString(), Encoding.UTF8);
        }

        private static int GetStableId(string text)
        {
            unchecked
            {
                uint hash = 2166136261;
                foreach (var ch in text)
                {
                    hash ^= ch;
                    hash *= 16777619;
                }

                var value = (int)(hash & 0x7fffffff);
                return value == 0 ? 1 : value;
            }
        }

        private static string SanitizeIdentifier(string text)
        {
            var builder = new StringBuilder(text.Length);
            foreach (var ch in text)
            {
                builder.Append(char.IsLetterOrDigit(ch) ? ch : '_');
            }

            if (builder.Length == 0 || !char.IsLetter(builder[0]) && builder[0] != '_')
            {
                builder.Insert(0, '_');
            }

            return builder.ToString();
        }

        private static string EscapeString(string text)
        {
            return text.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private sealed class Candidate
        {
            public Type Type;
            public int Id;
            public string EnumName;
            public string TypeReference;
            public string DisplayName;
        }
    }
}
